_target_: src.learners.VAT

# Common parameters
base_model: ${model}
tx: ${optimizer}
label_smoothing: 0
momentum_ema: 0.999
precision: ${precision}

# Method specific parameters
lambda_y: 50
unsup_warmup_pos: 0.4